# Sample GitHub Actions workflow to deploy and retrieve go packages to Artifactory

name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.19.4
        if: success()
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.4
      - name: Get dependencies
        if: success()
        run: go get -v -t -d ./...
      - name: tidy
        if: success()
        run: go mod tidy
      - name: Build
        if: success()
        #run: go build -v ./... -o ./dist/artifactory-demo
        run: go build -o dist/artifactory-demo
      - name: Bump version and push tag
        if: success()
        #uses: anothrNick/github-tag-action@1.36.0
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          INITIAL_VERSION: v0.0.1
          VERBOSE: true
          DEFAULT_BUMP: patch
        id: tag_version
      - name: Create a GitHub release
        if: success()
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }} 
      - name: publish to artifactory
        if: success()
        uses: nomadops/jfrog-cli-action@v0.0.4
        with:
          url: ${{ secrets.RT_URL }}
          credentials type: 'username'
          password: ${{ secrets.RT_APIKEY }}
          user: ${{ secrets.RT_USER }}
          args: gp ${{ steps.tag_version.outputs.new_tag }} --server-id rt-server
      - name: download from artifactory
        if: success()
        uses: nomadops/jfrog-cli-action@v0.0.4
        with:
          url: ${{ secrets.RT_URL }}
          credentials type: 'username'
          password: ${{ secrets.RT_APIKEY }}
          user: ${{ secrets.RT_USER }}
          args: rt dl "/artifactory-demo/${{ steps.tag_version.outputs.new_tag }}/artifactory-demo" "dist/artifactory-demo" --build-name=artifactory-demo --build-number=${{ steps.tag_version.outputs.new_tag }}
